### ISSUE TITLE
failed to download

### ISSUE THREAD

**Issue by fattikus** [45Drives/cockpit-navigator#22]
Files are not downloading via the context menu 'Download' option.

![image](https://user-images.githubusercontent.com/19525003/126849010-440b89c2-0f1c-471f-84b1-05c057eb6ca3.png)
Failure:
![image](https://user-images.githubusercontent.com/19525003/126849032-98687cb4-1f12-49a7-b9e6-1c3a97328cd9.png)

generated download url:
https://192.168.1.172:9090/cockpit/channel/f6d8dee8de4adcaf0ed7024de1d8c7fa9d8a9fbd04e31131758e4db2279668d2?eyJwYXlsb2FkIjoiZnNyZWFkMSIsImJpbmFyeSI6InJhdyIsInBhdGgiOiIvdmdtb3VudC9mYXR0aS9TaGlub2JpL3ZpZGVvcy9SZ3pNOE03VUxYL3k3TTZqOUhPaUkvMjAyMS0wNy0yM1QxNi0xMC00Ny5tcDQiLCJzdXBlcnVzZXIiOnRydWUsIm1heF9yZWFkX3NpemUiOjI1NTA4NjAwMywiZXh0ZXJuYWwiOnsiY29udGVudC1kaXNwb3NpdGlvbiI6ImF0dGFjaG1lbnQ7IGZpbGVuYW1lPVwiMjAyMS0wNy0yM1QxNi0xMC00Ny5tcDRcIiIsImNvbnRlbnQtdHlwZSI6ImFwcGxpY2F0aW9uL3gteHosIGFwcGxpY2F0aW9uL29jdGV0LXN0cmVhbSJ9fQ==

**Comment by joshuaboud** [comment]
I've seen this issue before where network latency can cause some ftp timeout error, can you send the service logs for cockpit? Running `journalctl -u cockpit` and recreating the bug should show something about that if it's the same issue. I found a way before to increase this timeout limit at one point but can't seem to find it right now. I believe I got to it after searching the error message from the cockpit log though.

**Comment by fattikus** [comment]
hmm seems strange that it has to do with network latency since I am in a local environment. 
Could this error (ssl certificate) be the culprit?

`cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.`

Also running that cmd you gave me:  `journalctl -u cockpit`
resulted into this:
`couldn't read from connection: Peer failed to perform TLS handshake`

![image](https://user-images.githubusercontent.com/19525003/126865225-0e98aa92-e49a-47fb-8c13-b26fd43a8b7f.png)

**Comment by fattikus** [comment]
I figured it out. its because of the ssl certificate, I had to unblock from chrome settings for that specific domain/ip address.
If you know a way I can install a certificate it would be great. thanks

**Comment by joshuaboud** [comment]
Thanks for this info. I'll follow up here if I get anywhere with installing a certificate for cockpit.

**Comment by Draconikard** [comment]
Guide for more basic users:

-Go to your cockpit dashboard
-Click on the site information button. This will most likely show up as "Not Secure" to the left of your URL
-Click on site settings
-Change automatic downloads from "ask" to "allow"
-Refresh the cockpit page to enable your settings.

**Comment by traptegies** [comment]
> Guide for more basic users:
> 
> -Go to your cockpit dashboard -Click on the site information button. This will most likely show up as "Not Secure" to the left of your URL -Click on site settings -Change automatic downloads from "ask" to "allow" -Refresh the cockpit page to enable your settings.

You have to allow unsecure content, too, with today's version of chrome
