### ISSUE TITLE
info keeps stacking up when clicked

### ISSUE THREAD

**Issue by TheFlipside** [45Drives/cockpit-navigator#23]
when clicking the question mark at the bottom right the info gets displayed.

when it is clicked again the info is displayed again, this can be repeated probably indefinitely and the space will just keep piling up at the bottom of the screen.

i feel a better behavior would be if for a second click the already displayed space would close again.

**Comment by joshuaboud** [comment]
Hi, can you give some more information? What browser and operating system are you using? In both Firefox and Chrome, this does not happen. An invisible div covers the entire area behind the popup, making it impossible to click any buttons behind it.

**Comment by TheFlipside** [comment]
Hello, I can see the issue on my system with Linux Mint 20.1, tested both in firefox 90.0.2 and MS edge 92.0.902.62 beta

it is not really a button behind the div, it is the ? button which is to the right of the "show hidden files" and "toggle dark/light" buttons.
the ? button can be clicked multiple times and it keeps displaying the same info for each click, stacking the divs.

the server i installed this on is a ubuntu server 20.04.2 system with cockpit 215

**Comment by joshuaboud** [comment]
Oh I see, must have been some difference with the way Cockpit 215 includes the plugin. Thank you for this info, glad it's fixed after the update.
