### ISSUE TITLE
[BUG] Permissions and ownership reset on saving file after editing

### ISSUE THREAD

**Issue by joshuaboud** [45Drives/cockpit-navigator#29]
### Discussed in https://github.com/45Drives/cockpit-navigator/discussions/28

<div type='discussions-op-text'>

<sup>Originally posted by **sommerso** September 29, 2021</sup>
Hi, 

I'm want to use navigator as a GUI to edit /etc/mail/relay-domains. This will be an ACL for a jnr Windows Admin to administrate. 

My user is in visudo as well as the wheel group. I've managed to make /etc/mail the default landing page for Navigator and the file has rw-rw-rw permissions, however when I try to save my edit, I get a pop up

Operation not permitted. 

I changed ownership to my user and confirmed that my user can write to the file via the shell. However I'm still having issues with Navigator. 

What am I missing? </div>

**Comment by sommerso** [comment]
Thanks!
