### ISSUE TITLE
Font on Navigator not following other cockpit fonts.

### ISSUE THREAD

**Issue by PabloGrok** [45Drives/cockpit-navigator#31]
I just installed Navigator and it seems to work fine, but the font used is some sort of Times New Roman, instead of the non-serif fonts used on the rest of the cockpit interface. Is that OK? I would suggest to use similar fonts to the rest of the cockpit UI.

![Screenshot 2021-09-30 at 18-23-48 Navigator - servidor](https://user-images.githubusercontent.com/46336079/135493963-f2267f00-505b-41fb-ac9d-b94db8ea0412.png)

**Comment by joshuaboud** [comment]
Hi, are you accessing cockpit through Windows? And which web browser are you using?

**Comment by PabloGrok** [comment]
It was Windows and Firefox and Edge browsers. After many install/uninstall of the software, now I see the proper fonts. Can't tell how this happened. Sorry.

**Comment by joshuaboud** [comment]
That's a very odd occurrence but I'm glad it's fixed now
