### ISSUE TITLE
Download and upload not working 

### ISSUE THREAD

**Issue by DavidOnKali** [45Drives/cockpit-navigator#36]
## Bug Info

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Console Output**
- Firefox:
  - Go to the menu dropdown > Web Developer > Web Developer Tools > Console
  - Expand relevent error messages
  - Copy and paste console log
- Chrome
  - Press Ctrl+Shift+J
  - Expand relevent error messages
  - Copy and paste console log
- Safari
  - [Open console](https://balsamiq.com/support/faqs/browserconsole/#apple-safari)
  - Expand relevent error messages
  - Copy and paste console log
- Internet Explorer
  - Good luck

## Client Side

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

## Server Side
 - OS: [e.g. Ubuntu 20.04, Rocky 8]
 - Cockpit Version: [e.g. 235]

**Additional context**

**Comment by joshuaboud** [comment]
Hi, please edit your issue and fill out the bug template so we know what the problem is.

**Comment by joshuaboud** [comment]
closed due to lack of information
