### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by finnie2006** [45Drives/cockpit-navigator#40]
How can i update it

**Comment by joshuaboud** [comment]
To install it in the first place, did you follow "From GitHub Release", "From Source", or "From 45Drives Repositories"? If it is from GitHub Release, just follow the same steps as installing it. For from source, `cd` into the directory you cloned the repo to, run `git fetch`, `git pull`, then `git checkout v0.5.7` and run `sudo make install`. For the 45Drives repositories, it will update automatically with `apt upgrade` or `dnf update`
