### ISSUE TITLE
Support for Stream9/EL9?

### ISSUE THREAD

**Issue by Naheem** [45Drives/cockpit-navigator#46]
## Bug Info

i tried to install this on Centos Stream 9. The setup script for Centos 8 doesn't work. and copying the repo file manually still gives an error.

**To Reproduce**
1. Install repo file manually
2. Get following error:

`Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides /bin/mkdir needed by cockpit-navigator-0.5.8-2.el8.noarch
  - nothing provides /bin/rmdir needed by cockpit-navigator-0.5.8-2.el8.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use 
`

**Comment by fxrsliberty** [comment]
I forced the install and it works regardless of the "nothing provides" , however, it breaks DNF 
[root@kvm ~]# dnf update
Last metadata expiration check: 0:38:25 ago on Sat 23 Jul 2022 11:18:22 AM EDT.
Error: 
 Problem: cannot install the best update candidate for package cockpit-navigator-0.5.8-1.el8.noarch
  - nothing provides /bin/mkdir needed by cockpit-navigator-0.5.8-2.el8.noarch
  - nothing provides /bin/rmdir needed by cockpit-navigator-0.5.8-2.el8.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

This is one of my favorite utilities. it lets me see what ISOs i have downloaded among other things :D

**Comment by joshuaboud** [comment]
Glad you enjoy it! I would recommend following the instructions for installing from source for now to use on EL9. We are currently in the process of overhauling our build/package process and will eventually be supporting Rocky 9. I'm also in the process of overhauling navigator itself, so I assume we will be packaging for EL9 by the time that's done.

**Comment by Naheem** [comment]
Thanks for the response.

I am currently in no great rush as I am scoping out a personal project (the type where you buy a domain and then do nothing), but I will keep an eye out for when its packaged as rpm for EL9.

**Comment by Naheem** [comment]
This is in the EPEL9 repository now, so closing.
