### ISSUE TITLE
Some CSS styles are missing

### ISSUE THREAD

**Issue by hugmouse** [45Drives/cockpit-navigator#48]
Hello! 

Installed your plugin, but it seems some styles did not apply. Do you have any idea how I can fix this? I'm not sure if this is a bug, so I created a blank issue.

I have tested this issue by installing this plugin both with `make install` from source (ba615bd2f2d50cd0837f5e47a3b2491a6f0e8892) and by just downloading the .deb file and installing it. Im using debian and I use cockpit version 273.

If you need any details, please let me know

## Screenshot
<img width="950" alt="Some CSS issue 1" src="https://user-images.githubusercontent.com/44648612/181254307-1ccf9437-b39d-44bd-b61b-1ec62b1bc622.png">

----

<img width="950" alt="Some CSS issue 2" src="https://user-images.githubusercontent.com/44648612/181254999-3a847ca8-cb0a-47de-8ce2-1579d34d19eb.png">

**Comment by joshuaboud** [comment]
It seems that Cockpit removed `cockpit.css` in this recent pull request, included in Cockpit 273: cockpit-project/cockpit#17486. Before this, plugins could just put `<link href="../base1/cockpit.css" type="text/css" rel="stylesheet">` in the HTML `<head>`, which is what this version of navigator does. Certainly makes sense why they don't want to maintain their own version of Patternfly, but unfortunately this change breaks any plugins that import Patternfly this way. I will fix this shortly.

**Comment by whalehub** [comment]
@joshuaboud The same issue appears to affect [Cockpit ZFS Manager](https://github.com/45Drives/cockpit-zfs-manager).

![error](https://xbb.datahoarder.dev/VUSu3/bEYUvUKU65.png/raw)

**Comment by joshuaboud** [comment]
Thanks for confirming those, we will get them looked at shortly.
