### ISSUE TITLE
Browser-editable file check too restrictive

### ISSUE THREAD

**Issue by mitinoh** [45Drives/cockpit-navigator#50]
It's a simple txt file but with .txt extension, when i try to open it, make me download the file instead of visualizing it

**Comment by MrTomek** [comment]
and json files is the same

**Comment by joshuaboud** [comment]
Pretty sure I know where the issue is. Can you send your console log output from when you try to edit the file? It should say "Unknown mimetype:" followed by the file's mime. I'll get this fixed shortly.
