### ISSUE TITLE
Navigator screen is not loading locally

### ISSUE THREAD

**Issue by chandakanup** [45Drives/cockpit-navigator#69]
Hello, I am Anup Chandak. I'm interested in the project "Navigator plugin modernization" for GSoC 2023.
I am using ubuntu operating system and I followed all the process in readme file to set up cockpit-navigator. But Navigator screen is not loading locally.
Here are some images of what its looking like on my machine. I can login to cockpit with browser and access navigator option present there.

As stated in Docs here
https://docs.google.com/document/d/1PLf4ZO1qgc_yZL1aHkWGmvg9QKGaaMmyzBkG1SbJrKA/edit
I worked on webpack.config.js file and try to find issue with patternfly but as I am not able to run it 
locally I am unable to proceed.
Please guide how can I start working on this project.

![Screenshot from 2023-03-02 22-42-08](https://user-images.githubusercontent.com/85943077/222507240-b3b61d51-4de9-470e-87b8-e3a90ab850ee.png)

![Screenshot from 2023-03-02 22-41-44](https://user-images.githubusercontent.com/85943077/222508655-ac0018df-0906-417d-84ff-6fbfd7f98c6f.png)

**Comment by KKoukiou** [comment]
It's not but please let's not do work on top of this code, as we plan to rewrite it to React etc. https://github.com/cockpit-project/cockpit/wiki/GSoC-2023-topics#navigator-plugin-modernization

Start by making some small contribution in the main cockpit repo https://github.com/cockpit-project/cockpit/wiki/GSoC-2023-topics#how-to-start-contributing

Also please close this issue, as github issues are not meant for using it for mentoring help. Please contact me (kkoukiou) on IRC https://github.com/cockpit-project/cockpit/wiki/GSoC-2023-topics#contact
