### ISSUE TITLE
Fedora Support ?

### ISSUE THREAD

**Issue by RileyMarquis3** [45Drives/cockpit-navigator#72]
Since this and other projects by 45Drives already support EL7 and EL8, would it be possible to add support for Fedora?  I am aware that I could technically install via an El8 binary (possibly) or from source.  Just wondering in case this was a simple thing to implement as EL and Fedora are closely related.

**Comment by jibsaramnim** [comment]
In case it helps, `cockpit-navigator` is available in [Fedora's package repository](https://packages.fedoraproject.org/pkgs/cockpit-navigator/cockpit-navigator/), so you can install it directly on Fedora with `dnf install cockpit-navigator`.

**Comment by leachimus** [comment]
But unfortunately not in the current version... Can someone please provide that? The current release is available since october 2022 and you still can't install it on the fedora server.

**Comment by pktiuk** [comment]
> But unfortunately not in the current version.

This is an issue which should be reported to the maintainer f the fedora package, not to the navigator devs.   
I think this issue should be closed

**Comment by RileyMarquis3** [comment]
I can confirm that cockpit-navigator-0.5.10 *is* available in Fedora Rawhide, and can be built on a Fedora 38 system.
On Fedora 38, you can use '`dnf download --source cockpit-navigator`' (as root) or use sudo if desired.  Then you can simply use '`rpmbuild --rebuild cockpit-navigator-0.5.10-1.fc39.src.rpm`' to rebuild. 
From there you can navigate to your rpmbuild/RPMS/noarch folder and install with:
 '`dnf localinstall cockpit-navigator-0.5.10-1.fc38.noarch.rpm`'.
Closing this issue.
